### ISSUE TITLE
Use the standard zoonotify translations for content-types

### ISSUE THREAD

**Issue by dptolle** [SiLeBAT/zoonotify-cms#17]
**Please adhere to the naming/formatting conventions outlined in the CMS Readme**

- Should year be its onw collection type connected by relation? Or an enumeration? Or a RegEx controlled string?

- [x] Rename: **field** year to Sampling Year

- [x] Rename: **Content-type** Sampling Objective to MD Sampling Context

- [x] Rename: **Content-type** Sampling Point to MD Sampling Stage

- [x] Rename: **Content-type** Sampling Origin to MD Sample Type

- [x] Rename **Content-type** Animal Species Food Top Category to MD Animal Species/ Food category

- [x] Rename: **Content-type** Animal Species Production Direction Food to MD Animal species Production type/Food

- [x] Rename: **Content-type** State to MD Federal State
